### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by pombears** [albertony/dcompermex#1]
Hi Albertony

I'm trying to compile the files using the below command in VS 2017 Build Tools:

cl /EHsc AclMgmt.Cpp DComPerm.Cpp ListAcl.Cpp SDMgmt.Cpp SrvcMgmt.Cpp UtilS.Cpp Wrappers.Cpp /link /out:dcompermex.exe

When I do I receive errors regarding unresolved external links.

Just wondering if you have the exe version of dcompermex available to download, or can assist with compiling issue.

Sorry I didn't know the best place to post this!

Many Thanks

Anthony

**Comment by albertony** [comment]
You need to link with advapi32.lib:

cl /EHsc AclMgmt.Cpp DComPerm.Cpp ListAcl.Cpp SDMgmt.Cpp SrvcMgmt.Cpp UtilS.Cpp Wrappers.Cpp /link "advapi32.lib" /out:dcompermex.exe

You should also find the compiled exe in the [releases](https://github.com/albertony/dcompermex/releases) page.

**Comment by pombears** [comment]
Thanks very much Albertony - that worked!
It's my lack of understanding :)

The tool is a big help. 

We set machine-wide DCOM permissions via Group Policy for a Windows account we use to remotely poll machines for monitoring purposes. This itself creates the problem of no longer being able to verify the permission on the target machines via the Components Services (dcomcnfg.exe) as the "Edit Limits" button becomes greyed out (presumably due to the permissions now being controlled by Group Policy). As you'll know, you can read the registry keys where these permissions are stored:
HKLM\SOFTWARE\Microsoft\Ole\MachineAccessRestriction
HKLM\SOFTWARE\Microsoft\Ole\MachineLaunchRestriction

This is how I came across your tool looking for an answer to the issue.
Your tool does exactly that and will be useful for troubleshooting purposes. It's ace!

Thanks very much and for the quick response

Anthony

**Comment by albertony** [comment]
Glad it worked out! I am running it as part of an installation process to set permissions on a specific object, and that works well. Started using this tool to avoid modifying registry, especially handling the permissions set on the relevant keys. Please just let me know if you cant get it to work for you.

**Comment by pombears** [comment]
Hi Abertony


When I run the dcompermex.exe tool on a machine that hasn't had DCOM Machine Access and Machine Launch permissions applied via group policy, it does show me the permissions applied in the output. Both for the "-ma list" and "-ml list" command-line options. Unfortunately, I've just found that the tool doesn't show permissions as soon as we apply them via Group Policy. Essentially the same effect as with the "Edit Limits" buttons being greyed out in the Component Services console, preventing viewing the permissions from within that console


Below shows a sample of the output I get:


c:\temp>DComPermEx.exe -ma list
Machine access permission list:

WARNING: Machine-wide Access Group Policy may override these settings!
WARNING: Machine-wide Launch/Activate Group Policy may override these settings!
Remote and Local access permitted to \Everyone.
WARNING: Machine-wide Access Group Policy may override these settings!
WARNING: Machine-wide Launch/Activate Group Policy may override these settings!
Local access permitted to NT AUTHORITY\ANONYMOUS LOGON.
WARNING: Machine-wide Access Group Policy may override these settings!
WARNING: Machine-wide Launch/Activate Group Policy may override these settings!
Remote and Local access permitted to BUILTIN\Distributed COM Users.
WARNING: Machine-wide Access Group Policy may override these settings!
WARNING: Machine-wide Launch/Activate Group Policy may override these settings!
Remote and Local access permitted to BUILTIN\Performance Log Users.
WARNING: Machine-wide Access Group Policy may override these settings!
WARNING: Machine-wide Launch/Activate Group Policy may override these settings!
Local access permitted to APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES.
WARNING: Machine-wide Access Group Policy may override these settings!
WARNING: Machine-wide Launch/Activate Group Policy may override these settings!
Local access permitted to APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES.


I don't suppose there is a way for the exe tool to actually show group-policy applied DCOM permissions?


Many Thanks


Anthony



________________________________

**Comment by albertony** [comment]
I'm sorry, I don't know how this could be done.
