### ISSUE TITLE
Problem with localized names

### ISSUE THREAD

**Issue by AlxVD** [albertony/dcompermex#2]
Looks like not using correct codepage when printing security principals' names.

**Comment by albertony** [comment]
Are you running it in Windows Command Prompt? Does it show correct if you switch code page, in the command prompt instance, into your configured Windows code page, using the `chcp` command before running DcomPermEx?

E.g. for `ANSI Latin 1; Western European (Windows)`

```
chcp 1252
DComPermEx.exe ....
```

**Comment by AlxVD** [comment]
1. standard cmd.exe, yes.
2. no. Because LookupAccountSid returns localized names.

P.S. Possible trick/hack to fix this is to switch completely to Unicode:
a) switch VS project to Unicode and add
b) (void)_setmode(_fileno(stdout), _O_WTEXT); as a first line to main().

**Comment by albertony** [comment]
> 2\. no. Because LookupAccountSid returns localized names.

Returned in a different locale then yours?

**Comment by AlxVD** [comment]
It's not about locale actually. The problem is that console codepage and GUI codepage are different for many languages (ANSI versions). So only Unicode can help).

**Comment by AlxVD** [comment]
BTW, there is another bug with LookupAccountSid call - there is no check for call result. If it fails (and it does for some SIDs on current Win10) then incorrect value from the previous call is used.

**Comment by albertony** [comment]
Sure, in my setup console codepage is 850 while windows is 1252. I created a username with special characters and added to dcom settings, and then listed with dcompermex. Showed garbage by default. But after `chcp 1252` it shows it correctly.

**Comment by AlxVD** [comment]
Are you suggesting for every user to know theirs corresponding codepage)? And setting it manually every time)?

**Comment by albertony** [comment]
First of all I'm trying to get a clear picture of what the problem is. The initial issue description was kind of sparse..

**Comment by AlxVD** [comment]
Well - you reproduced it yourself with special characters.
The problem is in different codepages between GUI and console.

**Comment by AlxVD** [comment]
"Easy fix" - switch to Unicode or UTF8 ).

**Comment by albertony** [comment]
> "Easy fix" - switch to Unicode or UTF8 ).

Well... A can of worms, that is what it is! Note that this project is mainly a build of the original source code from Microsoft's Windows-classic-samples, with only some small improvements from my part. Making bigger changes or changes that introduce risk of regressions is out of the scope of my plans for it.

That said: I have added a minimal effort improvement that solves the case that I managed to reproduce, at least. Please try it out to see if it solves yours too. It is included in the recently published release 2.0.2, in case you want to try it out without building it yourself.
