### ISSUE TITLE
LookupAccountSid result not checked

### ISSUE THREAD

**Issue by AlxVD** [albertony/dcompermex#3]
There is a bug with LookupAccountSid call - there is no check for call result. If it fails (and it does for some SIDs on current Win10) then incorrect value from the previous call is used (printed).

P.S. And there is a larger problem with DACL: current code checks only for 2 types of ACEs; there could be more (audit for example).
The solution can be in printing and setting DACL in SDDL format.

**Comment by albertony** [comment]
Thanks for reporting. The bug should be fixed on master.
Also thanks for the DACL/SDDL tip, I will put it on my list. But this project is not at the very top of my priority list at the moment, to be honest.

**Comment by albertony** [comment]
Fix included in recently published release 2.0.2, in case you want to try it out without building it yourself.
